version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: payment_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: payment_api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/payment_db?sslmode=disable
    depends_on:
      - db

volumes:
  db_data: